### ISSUE TITLE
How Linux user can use it?

### ISSUE THREAD

**Issue by b-Istiak-s** [thelinuxuser-choice/Bombo#1]
You just created exe formatted file. But, what about Linux?

**Comment by thelinuxuser-choice** [comment]
@Istiakshovon use with wine 
https://www.winehq.org/

**Comment by 0xbitx** [comment]
import hashlib
from colorama import Fore, init, Style, Back
red = Fore.LIGHTRED_EX
cyan = Fore.LIGHTCYAN_EX
magenta = Fore.MAGENTA
blue = Fore.LIGHTBLUE_EX
green = Fore.GREEN
import os
os.system('cls' if os.name == 'nt' else 'clear')
import ctypes
ctypes.windll.kernel32.SetConsoleTitleW('Bombo - Combo Unhasher Tool by thelinuxuser-choice')
banner = f'{red}\n \n ▄▄▄▄    ▒█████   ███▄ ▄███▓ ▄▄▄▄    ▒█████  \n▓█████▄ ▒██▒  ██▒▓██▒▀█▀ ██▒▓█████▄ ▒██▒  ██▒\n▒██▒ ▄██▒██░  ██▒▓██    ▓██░▒██▒ ▄██▒██░  ██▒   [Author - thelinuxuser-choice]\n▒██░█▀  ▒██   ██░▒██    ▒██ ▒██░█▀  ▒██   ██░   [Discord - PwnTime]\n░▓█  ▀█▓░ ████▓▒░▒██▒   ░██▒░▓█  ▀█▓░ ████▓▒░   [Version - Free/Beta]\n░▒▓███▀▒░ ▒░▒░▒░ ░ ▒░   ░  ░░▒▓███▀▒░ ▒░▒░▒░ \n▒░▒   ░   ░ ▒ ▒░ ░  ░      ░▒░▒   ░   ░ ▒ ▒░    "Skids , I love you!"\n ░    ░ ░ ░ ░ ▒  ░      ░    ░    ░ ░ ░ ░ ▒  \n ░          ░ ░         ░    ░          ░ ░  \n      ░                           ░          \n              \n\n'
print(banner)
print(f'{green}This will showed unhashed combo and save it as unhashed_combo.txt')
from os import path
if path.exists('unhashed_combo.txt'):
    print('Removing old unhashed combo!...')
    os.remove('unhashed_combo.txt')
print(f'\n{blue}Enter the hashed combo list path:')
combo_path = input('>')
print(f'\n{blue}Enter the wordlist path  :')
passlist = input('>')
print('\n')
import ctypes
ctypes.windll.kernel32.SetConsoleTitleW(f'Bombo - Combo Unhasher Tool by thelinuxuser-choice |Hashed combo - {combo_path} | Wordlist - {passlist}')

def sha256(passlist):
    with open(passlist, 'r') as f:
        lines = f.readlines()
        for word in lines:
            enc_wrd = word.encode()
            digest = hashlib.sha256(enc_wrd.strip()).hexdigest().lower()
            if digest == hash_pass:
                print(f'{cyan}---------------------------------------------------')
                print(f'{cyan}         Password Found! --> {email}:' + word, end='')
                print(f'{cyan}---------------------------------------------------')
                f = open('unhashed_combo.txt', 'a+', encoding='utf-8')
                f.write(f'{email}:{word}')
                f.write('\n')
                break
            print(f'{magenta}trying : ' + word + '\n')

def md5(passlist):
    with open(passlist, 'r') as f:
        lines = f.readlines()
        for word in lines:
            enc_wrd = word.encode()
            digest = hashlib.md5(enc_wrd.strip()).hexdigest().lower()
            if digest == hash_pass:
                print(f'{cyan}---------------------------------------------------')
                print(f'{cyan}         Password Found! --> {email}:' + word, end='')
                print(f'{cyan}---------------------------------------------------')
                f = open('unhashed_combo.txt', 'a+', encoding='utf-8')
                f.write(f'{email}:{word}')
                f.write('\n')
                break
            print(f'{magenta}trying : ' + word, end='')

def sha1(passlist):
    with open(passlist, 'r') as f:
        lines = f.readlines()
        for word in lines:
            enc_wrd = word.encode()
            digest = hashlib.sha1(enc_wrd.strip()).hexdigest().lower()
            if digest == hash_pass:
                print(f'{cyan}---------------------------------------------------')
                print(f'{cyan}         Password Found! --> {email}:' + word, end='')
                print(f'{cyan}---------------------------------------------------')
                f = open('unhashed_combo.txt', 'a+', encoding='utf-8')
                f.write(f'{email}:{word}')
                f.write('\n')
                break
            print(f'{magenta}trying : ' + word, end='')

def sha512(passlist):
    with open(passlist, 'r') as f:
        lines = f.readlines()
        for word in lines:
            enc_wrd = word.encode()
            digest = hashlib.sha512(enc_wrd.strip()).hexdigest().lower()
            if digest == hash_pass:
                print(f'{cyan}---------------------------------------------------')
                print(f'{cyan}         Password Found! --> {email}:' + word, end='')
                print(f'{cyan}---------------------------------------------------')
                f = open('unhashed_combo.txt', 'a+', encoding='utf-8')
                f.write(f'{email}:{word}')
                f.write('\n')
                break
            print(f'{magenta}trying : ' + word, end='')

def sha384(passlist):
    with open(passlist, 'r') as f:
        lines = f.readlines()
        for word in lines:
            enc_wrd = word.encode()
            digest = hashlib.sha384(enc_wrd.strip()).hexdigest().lower()
            if digest == hash_pass:
                print(f'{cyan}---------------------------------------------------')
                print(f'{cyan}          Password Found! --> {email}:' + word, end='')
                print(f'{cyan}---------------------------------------------------')
                f = open('unhashed_combo.txt', 'a+', encoding='utf-8')
                f.write(f'{email}:{word}')
                f.write('\n')
                break
            print(f'{magenta}trying : ' + word, end='')

def sha224(passlist):
    with open(passlist, 'r') as f:
        lines = f.readlines()
        for word in lines:
            enc_wrd = word.encode()
            digest = hashlib.sha224(enc_wrd.strip()).hexdigest().lower()
            if digest == hash_pass:
                print(f'{cyan}---------------------------------------------------')
                print(f'{cyan}          Password Found! --> {email}:' + word, end='')
                print(f'{cyan}---------------------------------------------------')
                f = open('unhashed_combo.txt', 'a+', encoding='utf-8')
                f.write(f'{email}:{word}')
                f.write('\n')
                break
            print(f'{magenta}trying : ' + word, end='')
with open(combo_path) as f:
    for line in f:
        currentline = line.split(':')
        email = currentline[0]
        hash_pass2 = currentline[1]
        hash_pass1 = hash_pass2.strip('\n')
        hash_pass = hash_pass1.lower()
        if len(hash_pass) == 64:
            sha256(passlist)
        elif len(hash_pass) == 32:
            md5(passlist)
        elif len(hash_pass) == 128:
            sha512(passlist)
        elif len(hash_pass) == 40:
            sha1(passlist)
        elif len(hash_pass) == 96:
            sha384(passlist)
        elif len(hash_pass) == 56:
            sha224(passlist)
        else:
            print(f'{red}Hash not found. Check if its included in md5, sha1, sha224, sha256, sha384, sha512.')
